export const catchAsync = (fn: any) => (req: any, res: any) => fn(req, res).catch((err: any) => res.status(400).json({err}))